#!/usr/bin/perl

open(FHR,"<","test1.txt") or die "Nope";
use strict;

#my $test=<FHR>;
my  $tn = '';
 
for (<FHR>){
	next if /^#/;
	next if /^\n/;
	$tn = $_;
	#$tn =~ s/$/,/;	
	my ($name , $Id , $code , $city) = split /,/,$tn;
	#print "Name:$name\n","ID:$Id\n","Code:$code\n","City:$city\n";
	my $input=<STDIN>;
	if($input == $name){

		print "yes";
	}
}
close(FHR) or die "nope";






